name: candlecatch
description: "A new Flutter project."

publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_hooks: ^0.21.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/signInPageImage.png

  fonts:
    - family: Corporate Logo Rounded Bold
      fonts:
        - asset: fonts/Corporate-Logo-Rounded-Bold-ver3/Corporate-Logo-Rounded-Bold-ver3.otf
